import hashlib
import logging
import warnings
from typing import List
from dotenv import load_dotenv

from google.genai.types import Part
from google.adk.models import LlmResponse, LlmRequest
from google.adk.agents.callback_context import CallbackContext

load_dotenv()
logger = logging.getLogger(__name__)
warnings.filterwarnings("ignore", category=UserWarning, module=".*pydantic.*")


async def _process_user_uploaded_artifact(
    part: Part, 
    callback_context: CallbackContext
) -> List[Part]:    
    filename = part.inline_data.display_name or "uploaded_image"

    logger.debug(
        "Starting artifact processing for user-uploaded part with display name: %s", 
        filename
    )

    hash_input = filename.encode("utf-8") + part.inline_data.data
    content_hash = hashlib.sha256(hash_input).hexdigest()[:16]

    mime_type = part.inline_data.mime_type
    extension = mime_type.split("/")[-1]

    artifact_id = f"input_image_{content_hash}.{extension}"

    logger.info("Checking for existence of artifact ID: %s", artifact_id)

    try:
        if artifact_id not in await callback_context.list_artifacts():
            await callback_context.save_artifact(
                filename=artifact_id, 
                artifact=part
            )
            logger.debug("Successfully saved artifact: %s", artifact_id)
            
        else:
            logger.debug("Artifact already exists: %s", artifact_id)

    except Exception as error:
        logger.error("Error processing user-uploaded artifact: %s", error, exc_info=True)

    caption = f"""
    [User Uploaded Artifact] 
    Below is the content of artifact ID : {artifact_id}
    """

    return [Part(text=caption), part]

async def _process_generated_artifact(
    part: Part, callback_context: CallbackContext
) -> List[Part]:
    logger.debug("Starting artifact processing for tool-generated part.")

    artifact_id = part.function_response.response.get("tool_response_artifact_id")

    if not artifact_id:
        logger.warning("No artifact generated by tool. Returning original part.")
        return [part]

    logger.info("Attempting to load generated artifact: %s", artifact_id)

    try:
        artifact = await callback_context.load_artifact(filename=artifact_id)
        logger.debug("Successfully loaded generated artifact: %s", artifact_id)
    
    except Exception as error:
        logger.error("Error loading generated artifact ID %s: %s", artifact_id, error, exc_info=True)

    caption = f"""
    [Tool Response Artifact] 
    Below is the content of artifact ID : {artifact_id}
    """

    return [part, Part(text=caption), artifact]

async def before_root_agent_model_callback(
    callback_context: CallbackContext, 
    llm_request: LlmRequest
) -> LlmResponse | None:
    logger.info("Executing before_root_agent_model_callback.")
    
    content_count = len(llm_request.contents)
    logger.debug("LLM Request contains %d content block(s).", content_count)

    for content_idx, content in enumerate(llm_request.contents):
        if not content.parts:
            logger.warning("Content block %d has no parts. Skipping.", content_idx)
            continue

        request_parts = []

        part_count = len(content.parts)
        logger.debug("Content block %d has %d parts to process.", content_idx, part_count)

        for idx, part in enumerate(content.parts):
            if part.inline_data:
                part_type = "InlineData (User Upload)"
                processed_parts = await _process_user_uploaded_artifact(
                    part, 
                    callback_context
                )
            
            elif part.function_response:
                func_name = part.function_response.name
                part_type = f"FunctionResponse: {func_name}"

                if part.function_response.name in [
                    "generate_image_tool", 
                    "change_background_capability_tool", 
                    "change_background_fast_tool",
                ]:
                    processed_parts = await _process_generated_artifact(
                        part, 
                        callback_context
                    )

                else:
                    processed_parts = [part]
                    logger.debug(
                        "Skipping artifact processing for unhandled function response: %s", 
                        func_name
                    )

            else:
                part_type = "Text"
                processed_parts = [part]

            logger.debug(
                "Part %d/%d (Type: %s) processed. %d new parts generated.", 
                idx + 1, 
                part_count, 
                part_type,
                len(processed_parts)
            )

            request_parts.extend(processed_parts)

        content.parts = request_parts

    logger.info("Finished execution of before_root_agent_model_callback.")
    return None