import os
from dotenv import load_dotenv

load_dotenv()


IMAGE_EDIT_AGENT_MODEL: str = os.getenv("IMAGE_EDIT_AGENT_MODEL")

IMAGE_EDIT_AGENT_MAX_TOKENS: int = 4096
IMAGE_EDIT_AGENT_TEMPERATURE: float = 0.3

IMAGE_BACKGROUND_FAST_TOOL_MODEL: str = os.getenv("IMAGE_BACKGROUND_FAST_TOOL_MODEL")
IMAGE_BACKGROUND_CAPABILITY_TOOL_MODEL: str = os.getenv("IMAGE_BACKGROUND_CAPABILITY_TOOL_MODEL")
